# Generated by Django 4.1.7 on 2023-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumdetail',
            name='release_title',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='this is a comment'),
            preserve_default=False,
        ),
    ]
