# Generated by Django 4.1.7 on 2023-03-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_rename_label_albumdetail_tracklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdetail',
            name='api_key',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='albumdetail',
            name='tracklist',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
