# Generated by Django 4.1.7 on 2023-03-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_albumdetail_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumdetail',
            name='api_key',
        ),
    ]
