# Generated by Django 4.1.7 on 2023-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_rename_album_album_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumdetail',
            name='genre',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='albumdetail',
            name='tracks',
            field=models.JSONField(null=True),
        ),
    ]
