# Generated by Django 4.1.7 on 2023-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_albumdetail_genre_albumdetail_tracks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='details',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='albumdetail',
            name='api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
