# Generated by Django 4.1.7 on 2023-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_rename_detail_album_album_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
    ]
