# Generated by Django 4.1.7 on 2023-03-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_alter_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdetail',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
    ]
