# Generated by Django 4.1.7 on 2023-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_alter_albumdetail_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdetail',
            name='api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
