# Generated by Django 4.1.7 on 2023-03-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_alter_albumdetail_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_detail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='albums.albumdetail'),
        ),
    ]
