# Generated by Django 4.1.7 on 2023-03-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_alter_album_album_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_detail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='albums.albumdetail'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='albums.album'),
        ),
    ]
